### ISSUE TITLE
Generic aggregation function

### ISSUE THREAD

**Issue by sbfnk** [reichlab/hubEnsembles#14]
I wonder if it would be good to support generic aggregation functions instead of the current mean/median/`MatrixStats` functions? it would potentially remove the dependency on `MatrixStats` while allowing the user to choose different methods for aggregation (e.g. a different weighted median method).

Example calls would be

```{r}
build_quantile_ensemble(df, method = mean)
build_quantile_ensemble(df, method = MatrixStats::weightedMean, weights = weights)
build_quantile_ensemble(df, method = cNORM::weighted.quantile, probs = 0.5, weights = weights)
```

A benefit of this approach would be avoiding the code multiplication in https://github.com/reichlab/hubEnsembles/blob/17d59d86244b64ff7a0919af5d45e0a3e8f57c49/R/build_quantile_ensemble.R#L42 (which would become a single call instead of 4 paths). A complication would be how to pass the weights so that they're associated with the correct models.

**Comment by elray1** [comment]
Hi Seb -- this package is actually out of date. The one we're working on as part of hubverse is [here](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles).

The equivalent function there is called `simple_ensemble`, and it does support the provision of a user-specified aggregation function via the `agg_fun` [argument](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles/blob/bfc131746de6fccd5641208248f1b130010dd2f3/R/simple_ensemble.R#L15C1-L17). There is still some manual branching in there as a user convenience, so that you can just specify `"median"` if you want a weighted median and you'll get the expected result back. But I think the general thing you were after here is supported.

I'm going to close this issue, but please do file an issue on the hubverse repo if you have more follow up comments/ideas.

**Comment by sbfnk** [comment]
> this package is actually out of date. The one we're working on as part of hubverse is [here](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles).

Ahhhh, that explains it being a bit bare-bones. Perhaps delete this repo to avoid others getting similarly confused? Will have a look at the other one and comment there if appropriate.

**Comment by elray1** [comment]
Unfortunately, use of this package is baked into a couple of our processes, so deleting it is not an option in the short term. However, I just updated the readme to link to the hubverse hubEnsembles package.
